Update Readme.md
Front-znad-zatoki/super-farmer pull request #131
Opened 2021-02-12 13:43 UTC by SebastianBabinski1

closed #102

2021-02-12 18:43 UTC, vieraboschkova commented on README.md
> +Special thanks for our mentor Aleksander!
change to: ..thanks to our...

2021-02-12 18:44 UTC, vieraboschkova requested changes
tiny spelling and good to go!

2021-02-15 16:22 UTC, synowa submitted a review, later dismissed
Looks good

2021-02-15 17:04 UTC, vieraboschkova submitted a review, later dismissed

2021-02-15 18:03 UTC, synowa approved these changes

2021-02-15 18:07 UTC, Enessetere approved these changes
well done

2021-02-15 18:07 UTC, merged