Refactor/#73 modify players herd
Front-znad-zatoki/super-farmer pull request #76
Opened 2021-01-31 00:10 UTC by vieraboschkova

closes #73

2021-01-31 13:08 UTC, vieraboschkova commented
closes #73 
unused imports to be removed after full refactor

2021-02-01 08:30 UTC, Enessetere requested changes
Consider mentioned changes.
Why are you creating herdConfigInterface, if you are creating playerHerdInterface?

2021-02-01 08:30 UTC, Enessetere commented on src/Interfaces/GameConfigInterface.ts
> +}
Consider adding protectorAnimalInterface, also split these interfaces into separate files.

2021-02-01 08:30 UTC, Enessetere commented on src/Player.ts
> +    }[],
Consider using here interface type, not type declaration. Adjust interface if necessary.

2021-02-01 08:30 UTC, Enessetere commented on src/app/View.ts
> +    // );
Consider removing unnecessary comments, as initializePlayer is no longer available in GameController.

2021-02-01 08:30 UTC, Enessetere commented on src/app/logic/Bank.ts
> +// import { Herd } from './Herd';
Consider removing unnecessary comment

2021-02-01 08:30 UTC, Enessetere commented on src/app/logic/Bank.ts
> +    }[],
Consider using interace in contructor. Adjust if necessary.

2021-02-01 08:30 UTC, Enessetere commented on src/app/logic/Herd.ts
> +    }[],
Consider using herd config interface.

2021-02-01 08:30 UTC, Enessetere commented on src/app/logic/Herd.ts
> +    const indexOfAnimal = this.animals.findIndex((animal) => {
Destructuring will improve readability

2021-02-01 08:30 UTC, Enessetere commented on test/herd.spec.ts
> +// const newHerd = new Herd(mockHerdConfig);
1-16 - Remove unused imports and unnecessary comment

2021-02-01 21:39 UTC, paula0403 commented on src/Animals/Animal.ts
> +// export abstract class Animal {
remove this comment

2021-02-01 21:39 UTC, Enessetere approved these changes
Looks good to me

2021-02-01 21:40 UTC, vieraboschkova commented on src/Animals/Animal.ts
> +// export abstract class Animal {
will do in refactor

2021-02-01 21:48 UTC, paula0403 approved these changes

2021-02-01 21:49 UTC, paula0403 approved these changes

2021-02-01 21:50 UTC, merged